BEGIN;

INSERT INTO price_bands (category, component, product, unit, rate_low, rate_high, wastage_pct, min_charge, notes) VALUES
    ('Carpet', 'floor', 'Carpet + pad', 'sqft', 2.00, 5.00, 10, 300.00, NULL),
    ('Vinyl', 'floor', 'Sheet vinyl', 'sqft', 2.00, 5.00, 15, 250.00, NULL),
    ('Laminate', 'floor', 'Laminate standard', 'sqft', 4.00, 8.00, 10, 350.00, NULL),
    ('Laminate', 'floor', 'Laminate premium (water-resistant)', 'sqft', 6.00, 10.00, 10, 350.00, NULL),
    ('LVP', 'floor', 'Luxury vinyl plank / tile', 'sqft', 4.50, 9.00, 10, 400.00, 'US avg ~6.50'),
    ('Wood', 'floor', 'Engineered wood', 'sqft', 7.00, 14.00, 10, 450.00, 'US avg ~10.50')
ON CONFLICT (category, component, coalesce(product, '')) DO NOTHING;

INSERT INTO pricing_rules (rule_key, val_low, val_high, notes) VALUES
    ('labor_only', 2.00, 6.00, 'per sqft if customer supplies material'),
    ('old_floor_removal', 1.50, 3.50, 'per sqft, by type'),
    ('subfloor_leveling', 2.00, 5.00, 'per sqft; TX slab moisture -> survey'),
    ('herringbone_labor', 8.00, 12.00, 'per sqft pattern; +15% waste'),
    ('travel_fee', 50.00, 150.00, 'edge / farther in service area')
ON CONFLICT (rule_key) DO NOTHING;

INSERT INTO service_area (city, zip, zone, notes) VALUES
    ('Austin', NULL, 'core', NULL),
    ('Round Rock', NULL, 'core', NULL),
    ('Cedar Park', NULL, 'core', NULL),
    ('Pflugerville', NULL, 'core', NULL),
    ('Leander', NULL, 'core', NULL),
    ('Manor', NULL, 'core', NULL),
    ('Hutto', NULL, 'core', NULL),
    ('Buda', NULL, 'core', NULL),
    ('Kyle', NULL, 'core', NULL),
    ('Lakeway', NULL, 'core', NULL),
    ('Bee Cave', NULL, 'core', NULL),
    ('Del Valle', NULL, 'core', NULL),
    ('West Lake Hills', NULL, 'core', NULL),
    ('Sunset Valley', NULL, 'core', NULL),
    ('Georgetown', NULL, 'edge', '~28 mi'),
    ('Dripping Springs', NULL, 'edge', '~25 mi'),
    ('Elgin', NULL, 'edge', '~25 mi'),
    ('Liberty Hill', NULL, 'edge', '~30 mi'),
    ('San Marcos', NULL, 'edge', '~30 mi'),
    ('Bastrop', NULL, 'edge', '~30 mi'),
    ('Wimberley', NULL, 'edge', '~30 mi'),
    ('Taylor', NULL, 'edge', '~30 mi'),
    ('Jarrell', NULL, 'edge', '~35 mi'),
    ('Dallas', NULL, 'out', NULL),
    ('Houston', NULL, 'out', NULL),
    ('San Antonio', NULL, 'out', NULL),
    ('Fort Worth', NULL, 'out', NULL),
    ('Waco', NULL, 'out', NULL),
    ('Killeen', NULL, 'out', NULL),
    ('Temple', NULL, 'out', NULL),
    ('New Braunfels', NULL, 'out', NULL),
    ('College Station', NULL, 'out', NULL),
    ('El Paso', NULL, 'out', NULL),
    ('Corpus Christi', NULL, 'out', NULL),
    ('Lubbock', NULL, 'out', NULL),
    ('Austin', '78701', 'core', NULL),
    ('Austin', '78702', 'core', NULL),
    ('Austin', '78703', 'core', NULL),
    ('Austin', '78704', 'core', NULL),
    ('Austin', '78705', 'core', NULL),
    ('Austin', '78717', 'core', NULL),
    ('Austin', '78719', 'core', NULL),
    ('Austin', '78721', 'core', NULL),
    ('Austin', '78722', 'core', NULL),
    ('Austin', '78723', 'core', NULL),
    ('Austin', '78724', 'core', NULL),
    ('Austin', '78725', 'core', NULL),
    ('Austin', '78726', 'core', NULL),
    ('Austin', '78727', 'core', NULL),
    ('Austin', '78728', 'core', NULL),
    ('Austin', '78729', 'core', NULL),
    ('Austin', '78730', 'core', NULL),
    ('Austin', '78731', 'core', NULL),
    ('Austin', '78732', 'core', NULL),
    ('Austin', '78733', 'core', NULL),
    ('Austin', '78735', 'core', NULL),
    ('Austin', '78736', 'core', NULL),
    ('Austin', '78737', 'core', NULL),
    ('Austin', '78739', 'core', NULL),
    ('Austin', '78741', 'core', NULL),
    ('Austin', '78742', 'core', NULL),
    ('Austin', '78744', 'core', NULL),
    ('Austin', '78745', 'core', NULL),
    ('Austin', '78746', 'core', NULL),
    ('Austin', '78747', 'core', NULL),
    ('Austin', '78748', 'core', NULL),
    ('Austin', '78749', 'core', NULL),
    ('Austin', '78750', 'core', NULL),
    ('Austin', '78751', 'core', NULL),
    ('Austin', '78752', 'core', NULL),
    ('Austin', '78753', 'core', NULL),
    ('Austin', '78754', 'core', NULL),
    ('Austin', '78756', 'core', NULL),
    ('Austin', '78757', 'core', NULL),
    ('Austin', '78758', 'core', NULL),
    ('Austin', '78759', 'core', NULL),
    ('Round Rock', '78664', 'core', NULL),
    ('Round Rock', '78665', 'core', NULL),
    ('Round Rock', '78681', 'core', NULL),
    ('Cedar Park', '78613', 'core', NULL),
    ('Cedar Park', '78630', 'core', NULL),
    ('Pflugerville', '78660', 'core', NULL),
    ('Pflugerville', '78691', 'core', NULL),
    ('Leander', '78641', 'core', NULL),
    ('Leander', '78646', 'core', NULL),
    ('Manor', '78653', 'core', NULL),
    ('Hutto', '78634', 'core', NULL),
    ('Buda', '78610', 'core', NULL),
    ('Kyle', '78640', 'core', NULL),
    ('Lakeway', '78734', 'core', NULL),
    ('Bee Cave', '78738', 'core', NULL),
    ('Del Valle', '78617', 'core', NULL),
    ('Georgetown', '78626', 'edge', NULL),
    ('Georgetown', '78628', 'edge', NULL),
    ('Georgetown', '78633', 'edge', NULL),
    ('Dripping Springs', '78620', 'edge', NULL),
    ('Elgin', '78621', 'edge', NULL),
    ('Liberty Hill', '78642', 'edge', NULL),
    ('San Marcos', '78666', 'edge', NULL),
    ('Bastrop', '78602', 'edge', NULL),
    ('Wimberley', '78676', 'edge', NULL),
    ('Taylor', '76574', 'edge', NULL),
    ('Jarrell', '76537', 'edge', NULL),
    ('Dallas', '75201', 'out', NULL),
    ('Houston', '77002', 'out', NULL),
    ('San Antonio', '78205', 'out', NULL),
    ('Fort Worth', '76102', 'out', NULL),
    ('Waco', '76701', 'out', NULL),
    ('Killeen', '76541', 'out', NULL),
    ('Temple', '76501', 'out', NULL),
    ('New Braunfels', '78130', 'out', NULL),
    ('College Station', '77840', 'out', NULL),
    ('El Paso', '79901', 'out', NULL),
    ('Corpus Christi', '78401', 'out', NULL)
ON CONFLICT (lower(city), coalesce(zip, '')) DO NOTHING;

INSERT INTO reply_templates (key, body, sends_automatically, notes) VALUES
    ('needs_area',
     'Thanks for getting in touch. To price this I need one more thing: roughly how many square feet is the floor? A rough number is fine — I can firm it up on site.',
     true,
     'sent when the material is known and the area is not'),
    ('needs_material',
     'Thanks for getting in touch. What are you thinking of putting down — luxury vinyl plank, laminate, engineered wood, sheet vinyl or carpet?',
     true,
     'sent when the area is known and the material is not'),
    ('needs_both',
     'Thanks for getting in touch. Two things and I can put a number on it: what are you thinking of putting down, and roughly how many square feet is the floor?',
     true,
     'sent when neither the material nor the area is known'),
    ('needs_location',
     'Thanks for getting in touch. Whereabouts is the property? I work in Austin and about thirty miles around it.',
     true,
     'sent when the town is not known'),
    ('rates_preamble',
     'Here is what it costs, installed. That covers the material, underlay, fitting, and taking the old covering away.',
     true,
     'introduces the rate lines; the rates themselves come from price_bands, never from here'),
    ('out_of_area',
     E'Thanks for thinking of me. I work in Austin and about thirty miles around it, so this one is outside what I can reach.\n\nI have not put a price on it, because a number for a job I cannot take is no use to you. If you are ever closer, do write again.',
     true,
     'sent instead of a price when the property is outside the service area; carries no figure by design'),
    ('signature',
     E'\n\nBest,\nthe flooring desk',
     true,
     'appended to every reply'),
    ('nudge',
     E'Just checking this is still on your mind. If you would like me to pick it up, reply and I will carry on from where we left off.\n\nIf the timing has changed, no reply needed, I will close it off and you can write again whenever suits.',
     true,
     'sent once to an order that has gone quiet; carries no figure and repeats no question'),
    ('quote_opening',
     'Thanks for the details. Here is what this job comes to, based on the price list as it stands today.',
     false,
     'the first line of a letter carrying a price -- never sent without a person, and the code will not send it to a customer at all'),
    ('after_a_service_answer',
     'To put a number on it I need two things: roughly how many square feet, and whereabouts the property is. A rough size is fine — I can firm it up on site.',
     true,
     'follows the answer to "do you do X?", but only when the answer is yes'),
    ('quote_closing',
     E'The spread covers the options listed above and what the floor turns out to look like once the old covering is up. Tell me which one you have in mind and I can narrow it down, or I can firm it up on site. The price holds for 30 days.\n\nHappy to answer anything before you decide.',
     false,
     'the last paragraph of a letter carrying a price')
ON CONFLICT (key) DO NOTHING;

INSERT INTO services (priority, label, we_do, match_words, answer, notes) VALUES
    (20, 'laminate', true, 'laminate', 'Yes, we install laminate.', NULL),
    (30, 'engineered wood', true, 'engineered|hardwood|wood floor', 'Yes, we install engineered and solid hardwood.', NULL),
    (40, 'sheet vinyl', true, 'sheet vinyl|linoleum', 'Yes, we install sheet vinyl.', NULL),
    (60, 'tile and stone', false, 'tile|porcelain|ceramic|mosaic|marble|granite|natural stone|thinset|mortar|grout', 'We do not install tile or stone — we work with plank, laminate, vinyl and carpet. Happy to recommend a tile setter.', 'no price band exists'),
    (70, 'epoxy and garage coatings', false, 'epoxy|garage coating|polyaspartic', 'We do not do epoxy or garage coatings.', NULL),
    (80, 'hardwood refinishing', false, 'refinish|sand(ing)? (the )?floors?|re-?stain', 'We install new floors but do not refinish existing hardwood.', NULL),
    (90, 'concrete polishing', false, 'polished concrete|concrete polish|stain(ed)? concrete', 'We do not do polished or stained concrete.', NULL),
    (100, 'carpet cleaning', false, 'carpet clean|steam clean|shampoo', 'We install carpet but do not clean it.', NULL),
    (10, 'luxury vinyl plank', true, 'lvp|lvt|luxury vinyl|vinyl plank|vinyl tile|spc|wpc|rigid core', 'Yes, LVP and rigid core are what we install most.', NULL),
    (50, 'carpet', true, 'carpet|carpet tile', 'Yes, we install carpet and pad.', NULL)
ON CONFLICT (lower(label)) DO NOTHING;

COMMIT;
